version: '3'

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - '5434:5432'

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=busyroom
